# Generated by Django 5.0.6 on 2024-05-23 13:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foxford_app', '0003_graduatedstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduatedstudent',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
